## **Problem Statement**

*   The dataset contains daily trading data for multiple global companies, including fields such as Open, High, Low, Close, Volume, Industry_Tag, Brand_Name, and other relevant stock indicators, categorized by industry and country.

*   The goal is to perform an in-depth stock market analysis using Pandas, focusing on data cleaning, daily return calculations, volatility analysis, industry trends, and correlation between brands and sectors using visualization tools.


*   After implementation, the analysis highlights the most volatile industries, top-performing brands and provides clear visual insights into market trends and inter-stock relationships, demonstrating effective data wrangling and exploratory analysis on real-world stock data.

## **Dataset Info**


**Date:** The date of the stock price data.

**Open:** The opening price of the stock on that date.

**High:** The highest price the stock reached during the trading day.

**Low:** The lowest price the stock reached during the trading day.

**Close:** The closing price of the stock on that date.

**Volume:** The trading volume, i.e., the number of shares traded on that date.

**Brand_Name:** The name of the brand or company.

**Ticker:** Ticker symbol for the stock.

**Industry_Tag:** The industry category or sector to which the brand belongs.

**Country:** The country where the brand is headquartered or primarily operates.

## **Import Libraries**

In [ ]:
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
import warnings
warnings.filterwarnings('ignore')

## **Load Data**

In [ ]:
df = pd.read_csv('/content/World_Stock_Prices_Dataset.csv')

## **Dataset Overview & Structure**

In [ ]:
df.head()

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,Brand_Name,Ticker,Industry_Tag,Country,Capital Gains
0,2025-03-20 00:00:00-04:00,386.899994,397.820007,385.799988,389.609985,4003800,0.0,0.0,adobe,ADBE,technology,usa,NaN
1,2025-03-20 00:00:00-04:00,131.100006,132.289993,130.210007,130.509995,378500,0.0,0.0,lvmh,LVMUY,luxury goods,france,NaN
2,2025-03-20 00:00:00-04:00,236.559998,241.759995,236.199997,239.009995,8321600,0.0,0.0,jpmorgan chase & co,JPM,finance,usa,NaN
3,2025-03-20 00:00:00-04:00,60.480000,61.020000,60.340000,60.619999,16503100,0.0,0.0,cisco,CSCO,technology,usa,NaN
4,2025-03-20 00:00:00-04:00,59.020000,59.290001,58.689999,59.230000,2840400,0.0,0.0,unilever,UL,consumer goods,netherlands,NaN

In [ ]:
df.tail()

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,Brand_Name,Ticker,Industry_Tag,Country,Capital Gains
305209,2000-01-03 00:00:00-05:00,13.822670,13.822670,13.675379,13.720699,48000,0.0,0.0,honda,HMC,automotive,japan,NaN
305210,2000-01-03 00:00:00-05:00,3.990652,4.061914,3.848129,3.990652,134500,0.0,0.0,nintendo,NTDOY,gaming,japan,NaN
305211,2000-01-03 00:00:00-05:00,31.512873,31.512873,30.431443,30.799129,6057400,0.0,0.0,costco,COST,retail,usa,NaN
305212,2000-01-03 00:00:00-05:00,38.147537,38.255972,35.935457,37.496925,53076000,0.0,0.0,cisco,CSCO,technology,usa,NaN
305213,2000-01-03 00:00:00-05:00,5.731675,5.793975,5.427959,5.482471,5825700,0.0,0.0,american eagle outfitters,AEO,apparel,usa,NaN

In [ ]:
df.shape

(305214, 13)

#### **Identifying key columns and understanding data types**

In [ ]:
df.columns

Index(['Date', 'Open', 'High', 'Low', 'Close', 'Volume', 'Dividends',
       'Stock Splits', 'Brand_Name', 'Ticker', 'Industry_Tag', 'Country',
       'Capital Gains'],
      dtype='object')

In [ ]:
df.dtypes

Date              object
Open             float64
High             float64
Low              float64
Close            float64
Volume             int64
Dividends        float64
Stock Splits     float64
Brand_Name        object
Ticker            object
Industry_Tag      object
Country           object
Capital Gains    float64
dtype: object

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 305214 entries, 0 to 305213
Data columns (total 13 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   Date           305214 non-null  object
 1   Open           305214 non-null  float64
 2   High           305214 non-null  float64
 3   Low            305214 non-null  float64
 4   Close          305214 non-null  float64
 5   Volume         305214 non-null  int64
 6   Dividends      305214 non-null  float64
 7   Stock Splits   305214 non-null  float64
 8   Brand_Name     305214 non-null  object
 9   Ticker         305214 non-null  object
 10  Industry_Tag   305214 non-null  object
 11  Country        305214 non-null  object
 12  Capital Gains  2 non-null       float64
dtypes: float64(7), int64(1), object(5)
memory usage: 30.3+ MB

## **Data Cleaning**

Sorting the data in ascendind order

In [ ]:
df = df.sort_values(by='Date').reset_index(drop=True)

In [ ]:
df.head()

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,Brand_Name,Ticker,Industry_Tag,Country,Capital Gains
0,2000-01-03 00:00:00-05:00,5.731675,5.793975,5.427959,5.482471,5825700,0.0,0.0,american eagle outfitters,AEO,apparel,usa,NaN
1,2000-01-03 00:00:00-05:00,14.968750,15.593750,14.687500,15.500000,7843200,0.0,0.0,amd,AMD,technology,usa,NaN
2,2000-01-03 00:00:00-05:00,36.457976,36.846240,34.788441,36.205605,53228400,0.0,0.0,microsoft,MSFT,technology,usa,NaN
3,2000-01-03 00:00:00-05:00,23.135441,23.295548,22.495014,23.075401,2870400,0.0,0.0,target,TGT,retail,usa,NaN
4,2000-01-03 00:00:00-05:00,9.653981,9.765803,9.355788,9.467610,3277800,0.0,0.0,southwest airlines,LUV,aviation,usa,NaN

In [ ]:
df.tail()

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,Brand_Name,Ticker,Industry_Tag,Country,Capital Gains
305209,2025-03-20 00:00:00-04:00,17.959999,17.959999,17.700001,17.770000,545600,0.0,0.0,nintendo,NTDOY,gaming,japan,NaN
305210,2025-03-20 00:00:00-04:00,106.820000,108.970001,105.379997,105.480003,1481100,0.0,0.0,crocs,CROX,footwear,usa,NaN
305211,2025-03-20 00:00:00-04:00,48.500000,49.349998,48.490002,49.000000,10706600,0.0,0.0,chipotle,CMG,food,usa,NaN
305212,2025-03-20 00:00:00-04:00,104.400002,106.669998,103.919998,104.199997,5853100,0.0,0.0,target,TGT,retail,usa,NaN
305213,2025-03-20 00:00:00-04:00,386.899994,397.820007,385.799988,389.609985,4003800,0.0,0.0,adobe,ADBE,technology,usa,NaN

Fix date column

In [ ]:
df['Date'] = pd.to_datetime(df['Date'],utc = True).dt.date

In [ ]:
df.head()

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,Brand_Name,Ticker,Industry_Tag,Country,Capital Gains
0,2000-01-03,5.731675,5.793975,5.427959,5.482471,5825700,0.0,0.0,american eagle outfitters,AEO,apparel,usa,NaN
1,2000-01-03,14.968750,15.593750,14.687500,15.500000,7843200,0.0,0.0,amd,AMD,technology,usa,NaN
2,2000-01-03,36.457976,36.846240,34.788441,36.205605,53228400,0.0,0.0,microsoft,MSFT,technology,usa,NaN
3,2000-01-03,23.135441,23.295548,22.495014,23.075401,2870400,0.0,0.0,target,TGT,retail,usa,NaN
4,2000-01-03,9.653981,9.765803,9.355788,9.467610,3277800,0.0,0.0,southwest airlines,LUV,aviation,usa,NaN

### **Standardizing Categorical Data**

Before moving to analysis, ensure data
consistency in categorical values:
Checking key categorical columns prevents errors in grouping, filtering, and aggregations

In [ ]:
categorical_columns = df.select_dtypes(include=['object', 'category']).columns.tolist()
print(categorical_columns)

['Date', 'Brand_Name', 'Ticker', 'Industry_Tag', 'Country']

In [ ]:
df['Brand_Name'].unique()

array(['american eagle outfitters', 'amd', 'microsoft', 'target',
       'southwest airlines', 'johnson & johnson', 'toyota', 'nike',
       'the coca-cola company', 'colgate palmolive', 'starbucks',
       'jpmorgan chase & co', 'logitech', 'the walt disney company',
       'philips', 'procter & gamble', 'nordstrom', 'cisco', '3m',
       'costco', 'nintendo', 'honda', 'foot locker', 'apple', 'nvidia',
       'the home depot', 'hershey company', 'fedex', 'american express',
       "mcdonald's", 'marriott', 'amazon', 'adobe', 'unilever', 'netflix',
       'salesforce / slack', 'google', 'chipotle', 'lvmh', 'crocs',
       'mastercard', 'adidas', 'delta air lines', 'visa', 'bmw group',
       'ubisoft', 'porsche', 'tesla', 'puma', 'hilton', 'shopify',
       'block', 'spotify', 'pinterest', 'zoom video communications',
       'uber', 'peloton', 'zoominfo', 'airbnb', 'roblox', 'coinbase'],
      dtype=object)

In [ ]:
df['Brand_Name'].nunique()

61

In [ ]:
df['Ticker'].unique()

array(['AEO', 'AMD', 'MSFT', 'TGT', 'LUV', 'JNJ', 'TM', 'NKE', 'KO', 'CL',
       'SBUX', 'JPM', 'LOGI', 'DIS', 'PHG', 'PG', 'JWN', 'CSCO', 'MMM',
       'COST', 'NTDOY', 'HMC', 'FL', 'AAPL', 'NVDA', 'HD', 'HSY', 'FDX',
       'AXP', 'MCD', 'MAR', 'AMZN', 'ADBE', 'UL', 'NFLX', 'CRM', 'GOOGL',
       'CMG', 'LVMUY', 'CROX', 'MA', 'ADDYY', 'DAL', 'V', 'BAMXF',
       'UBSFY', 'POAHY', 'TSLA', 'PMMAF', 'HLT', 'SHOP', 'SQ', 'SPOT',
       'PINS', 'ZM', 'UBER', 'PTON', 'ZI', 'ABNB', 'RBLX', 'COIN'],
      dtype=object)

In [ ]:
df['Ticker'].nunique()

61

In [ ]:
df['Industry_Tag'].unique()

array(['apparel', 'technology', 'retail', 'aviation', 'healthcare',
       'automotive', 'food & beverage', 'consumer goods', 'finance',
       'entertainment', 'manufacturing', 'gaming', 'footwear',
       'logistics', 'food', 'hospitality', 'e-commerce', 'luxury goods',
       'financial services', 'music', 'social media', 'fitness',
       'cryptocurrency'], dtype=object)

In [ ]:
df['Industry_Tag'].nunique()

23

In [ ]:
df['Country'].unique()

array(['usa', 'japan', 'switzerland', 'netherlands', 'france', 'germany',
       'canada'], dtype=object)

In [ ]:
df['Country'].nunique()

7

### **Handling Missing Data**

In [ ]:
df.isna().sum()

Date                  0
Open                  0
High                  0
Low                   0
Close                 0
Volume                0
Dividends             0
Stock Splits          0
Brand_Name            0
Ticker                0
Industry_Tag          0
Country               0
Capital Gains    305212
dtype: int64

In [ ]:
df.drop('Capital Gains',inplace=True,axis=1)

In [ ]:
df.isna().sum()

Date            0
Open            0
High            0
Low             0
Close           0
Volume          0
Dividends       0
Stock Splits    0
Brand_Name      0
Ticker          0
Industry_Tag    0
Country         0
dtype: int64

### **Handling Duplicated Data**

In [ ]:
df.duplicated().sum()

np.int64(0)

### **Data Type Corrections**

**Date** should be converted from **object** to **datetime64** since it is needed for time-series analysis.

In [ ]:
# Optional: convert frequent categorical columns to 'category' type to optimize performance
cat_cols = ['Ticker', 'Brand_Name', 'Industry_Tag', 'Country']
for col in cat_cols:
    df[col] = df[col].astype('category')

In [ ]:
df['Date'] = pd.to_datetime(df['Date'])

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 305214 entries, 0 to 305213
Data columns (total 12 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   Date          305214 non-null  datetime64[ns]
 1   Open          305214 non-null  float64
 2   High          305214 non-null  float64
 3   Low           305214 non-null  float64
 4   Close         305214 non-null  float64
 5   Volume        305214 non-null  int64
 6   Dividends     305214 non-null  float64
 7   Stock Splits  305214 non-null  float64
 8   Brand_Name    305214 non-null  category
 9   Ticker        305214 non-null  category
 10  Industry_Tag  305214 non-null  category
 11  Country       305214 non-null  category
dtypes: category(4), datetime64[ns](1), float64(6), int64(1)
memory usage: 19.8 MB

In [ ]:
df.head()

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,Brand_Name,Ticker,Industry_Tag,Country
0,2000-01-03,5.731675,5.793975,5.427959,5.482471,5825700,0.0,0.0,american eagle outfitters,AEO,apparel,usa
1,2000-01-03,14.968750,15.593750,14.687500,15.500000,7843200,0.0,0.0,amd,AMD,technology,usa
2,2000-01-03,36.457976,36.846240,34.788441,36.205605,53228400,0.0,0.0,microsoft,MSFT,technology,usa
3,2000-01-03,23.135441,23.295548,22.495014,23.075401,2870400,0.0,0.0,target,TGT,retail,usa
4,2000-01-03,9.653981,9.765803,9.355788,9.467610,3277800,0.0,0.0,southwest airlines,LUV,aviation,usa